<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DiGi.Core">
      <HintPath>..\..\DiGi.Geometry\bin\DiGi.Core.dll</HintPath>
    </Reference>
    <Reference Include="DiGi.Geometry">
      <HintPath>..\..\DiGi.Geometry\bin\DiGi.Geometry.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
